version: '2.1'
services:
  cs2dashboard:
    image: lov432/cs2-dashboard:latest
    container_name: cs2dashboard
    volumes:
      - ./dashboard-config:/app/config
    environment:
      - MAXMIND_LICENSE_KEY= # Maxmind License Key (optional for geolocation)
    ports:
      - 3000:3000
    restart: unless-stopped
