version: '2.1'
services:
  cs2:
    container_name: cs2
    environment:
      # Check out https://hub.docker.com/r/joedwards32/cs2 for more information
      - 'CS2_SERVERNAME='
      - 'CS2_PW='
      - 'CS2_GAMEALIAS=casual'
      - 'CS2_BOT_QUOTA=0'
      - 'CS2_STARTMAP=de_mirage'
      - 'CS2_RCONPW=veryweakrconpassword'
      - 'CS2_LAN=0'
    networks:
      cs2:
        ipv4_address: 10.0.50.2
    ports:
      - '27015:27015/udp'
      # - "27015:27015/tcp" # This is not required for dashboard to work correctly
    volumes:
      - ./cs2:/home/steam/cs2-dedicated/
      - ./steam:/home/steam/Steam
      - ./steamcmd:/home/steam/steamcmd
    image: joedwards32/cs2
    restart: unless-stopped

  cs2dashboard:
    image: lov432/cs2-dashboard:latest
    container_name: cs2dashboard
    networks:
      cs2:
        ipv4_address: 10.0.50.3
    environment:
      - SERVER_IP=10.0.50.2
      - SERVER_PORT=27015
      - RCON_PORT=27015
      - RCON_PASSWORD=veryweakrconpassword
      - MAXMIND_LICENSE_KEY= # Maxmind License Key (optional for geolocation)
      - ADMIN_PLUGIN_INSTALLED=false # Change this to true if you have CS2-SimpleAdmin plugin installed: https://github.com/daffyyyy/CS2-SimpleAdmin
      # MySQL used in CS2-SimpleAdmin (only required if using CS2-SimpleAdmin):
      - SQL_HOST=10.0.50.4
      - SQL_PORT=3306
      - SQL_USER=cs2
      - SQL_DB=cs2
      - SQL_PASSWORD=veryweakdbpassword
    ports:
      - 3000:3000
    restart: unless-stopped

  db:
    image: mysql
    container_name: cs2-db
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - 'MYSQL_ROOT_PASSWORD=veryweakdbrootpassword'
      - 'MYSQL_DATABASE=cs2'
      - 'MYSQL_USER=cs2'
      - 'MYSQL_PASSWORD=veryweakdbpassword'
    # ports:
    #   - 3306:3306 # This is not required for dashboard to work correctly
    networks:
      cs2:
        ipv4_address: 10.0.50.4
    restart: always

networks:
  cs2:
    name: cs2
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.50.0/24
